### ISSUE TITLE
What common attributes do we want from providers?

### ISSUE THREAD

**Issue by Tabrizian** [Genorch/Orchestration#4]
In here, we discuss what attributes do we want from providers. Personally, I think the following attributes are suitable and accessible from different providers as we have discussed earlier.

* Number of vCPUs.
* Amount of RAM
* Amount of Hard Drive

Any suggestions?
@SaeedAr @1995parham

**Comment by 1995parham** [comment]
* Number of NICs.

**Comment by Tabrizian** [comment]
@1995parham Do all providers, provide this feature?

**Comment by 1995parham** [comment]
yes, I think they must have this feature.

**Comment by 1995parham** [comment]
* Boot image (Ubuntu, Fedora, ...)

**Comment by Tabrizian** [comment]
The problem with images is that we don't have standard multi domain image registry to guarantee unified images across all providers.

**Comment by 1995parham** [comment]
ok, we can get the image name from the user, for example as base name like dockerfiles.

**Comment by Tabrizian** [comment]
The problem with images is that there is no central image registry which all of these providers agree with that. As you can see in SAVI there are tons of Ubuntu 16.04 image. Which one we should choose from?! We need an standard multi domain image registry. To provide common base images for all providers so that we can guarantee unification of these images across all providers.

**Comment by 1995parham** [comment]
Ok, I know ! I said we get it for every service from the user and if user say nothing we search for some ad-hoc standard from ourselves so .. just think it as easy as possible !

**Comment by Tabrizian** [comment]
To wrap up I think below attributes are enough for creating virtual machines:
* Boot image 
* Number of network interfaces
* Number of vCPUs
* Amount of Hard Drive
* Amount of RAM

**Comment by 1995parham** [comment]
Thanks bro 🙌
