### ISSUE TITLE
Flavors

### ISSUE THREAD

**Issue by Tabrizian** [Genorch/Orchestration#5]
Are flavors standard way of defining virtual machine resources across all providers or it is something specific to ```OpenStack```? @1995parham

**Comment by 1995parham** [comment]
flavor is specific to `OpenStack` but we have some similar stuff in other virtualization environment.

**Comment by Tabrizian** [comment]
So I think it's better not to include them in our structure file. What's your idea?

**Comment by 1995parham** [comment]
We define vm resources in stml then we can create them using flavor in `OpenStack` or other platform specific way. so you think this way is not good ?

**Comment by Tabrizian** [comment]
It's better to keep them 👍

**Comment by Tabrizian** [comment]
Feel free to reopen it if you think the issue exists still

**Comment by 1995parham** [comment]
Thanks ! 👍
